### ISSUE TITLE
slcan through socketcan should be made easy using Yukon

### ISSUE THREAD

**Issue by silverv** [OpenCyphal/yukon#121]
Right now the user would have to download the standard namespaces, add them to the .cyphal folder in their home directory, add the CYPHAL_PATH variable to their .bashrc (if they have one) or on Windows they would have to add the environment variable. Then they would have to do some debugging around these files and finally they would have to debug the enironment variables that Yakut uses and then they could use it.

**Comment by silverv** [comment]
The setup_slcan file should be put into a system binaries folder, otherwise it does not work

**Comment by silverv** [comment]
CYPHAL_PATH should be exported

**Comment by pavel-kirienko** [comment]
life is pain, Silver
