### ISSUE TITLE
Publish release binaries via GitHub Releases

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/yukon#200]
>Also, we need releases that are built by actions and released on github. Either that or we need a guide for users to build it themselves.

_Originally posted by @thirtytwobits in https://github.com/OpenCyphal-Garage/yukon/issues/98#issuecomment-1303853248_

**Comment by pavel-kirienko** [comment]
Release binaries are currently uploaded to files.zubax.com. We also need to mirror them here on GitHub.

**Comment by clyde-johnston** [comment]
PR #337 has been created for this issue.

Areas for possible development improvement:
1) Create SHA files during the build process to include with the binaries
2) Include release notes and installation documentation with the release.
3) Simplify the build process by allowing builds outside Python virtual environments; they are not required for builds on disposable runners. This would standardize the build between Linux and Windows platforms and reduce the number of platform-specific conditions in the workflow. See GH Action run [#100](https://github.com/OpenCyphal/yukon/actions/runs/4446980236) to see the error when it run outside `venv`.
