### ISSUE TITLE
Close all other instances of Yukon before starting a new one

### ISSUE THREAD

**Issue by Zentrus** [OpenCyphal/yukon#230]

**Comment by silverv** [comment]
I reproduced this, but you have to first launch Yukon twice (which will happen because users are impatient and not sure if it launched. It will stay stuck in the background and will prevent you from working with Yukon. I am fixing this already.

**Comment by silverv** [comment]
I first fixed it by making sure that two or more Yukon instances can work simultaneously here, now implementing the close functionality

**Comment by silverv** [comment]
It may not be necessary to close the processes, I wouldn't want to do it without asking the user and asking the user for anything is kind of difficult.

**Comment by silverv** [comment]
There are also no longer any invisible Yukon processes running in the background
