### ISSUE TITLE
ElectronJS does produce errors that do not affect Yukon but may spook the user

### ISSUE THREAD

**Issue by silverv** [OpenCyphal/yukon#265]
![image](https://user-images.githubusercontent.com/15844364/209711741-ebd58376-99b4-49b5-a4a3-3f764f3aa366.png)

**Comment by pavel-kirienko** [comment]
![image](https://user-images.githubusercontent.com/3298404/209713851-a253355e-42da-4a50-b393-a5dc33c524be.png)
