### ISSUE TITLE
Attaching to an SLCAN adapter shows weird msgs

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/yukon#300]
![image](https://user-images.githubusercontent.com/3298404/223752399-f8b3f81d-b29e-4248-8193-e0ebfca116e5.png)

The connection is established successfully but there's this "undefined" popup that doesn't go away.

I can reproduce this in the test room right now if needed.

**Comment by silverv** [comment]
doesn't really happen any more
