### ISSUE TITLE
Erratic publication over SLCAN after switching the transport from SocketCAN while keeping the publisher configured

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/yukon#322]
This one is complicated and requires a live demo.

**Comment by silverv** [comment]
Maybe the timeouts for publishing are too high and it accumulates a huge list to publish while its unable to do so.

**Comment by silverv** [comment]
that's just the delays of pythoncan, it takes hundreds of milliseconds to send a single small message
