### ISSUE TITLE
[transport] Cannot remove transport

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/yukon#327]
After several nodes appeared online and then disappeared, Yukon refused to remove the active transport with no errors in the log view or anywhere else; clicking "Remove" several times produced no effect. A few seconds later this happened:

![image](https://user-images.githubusercontent.com/3298404/224333302-a94ac2e0-b6eb-4981-a887-7aa60c58b889.png)

**Comment by silverv** [comment]
didn't reproduce
