### ISSUE TITLE
Yukon on windows does not work over SLCAN

### ISSUE THREAD

**Issue by sainquake** [OpenCyphal/yukon#402]
1. Connect sniffer to PC
2. Connect Cyphal node to sniffer
3. Run .exe file
4. Choose CAN -> SLCAN
5. Pressed 'Start this transport'
6. Node does not appear

![image](https://github.com/OpenCyphal/yukon/assets/9420261/373840db-9ff8-43ba-818a-4f3ea9f1f19b)

Can you help me? Am I doing everything in right way?

**Comment by sainquake** [comment]
Thats how it looks like before I press 'Start this transport'

![image](https://github.com/OpenCyphal/yukon/assets/9420261/6e2811bb-e82f-4c4b-8d41-51500e0942b0)

Just in case. everything work in Ubuntu with same sniffer device and can node (checked by @PonomarevDA )

**Comment by sainquake** [comment]
Is there any solution for windows? Cna you help me?

**Comment by silverv** [comment]
Try using Ubuntu or any other GNU/Linux distro

**Comment by silverv** [comment]
https://rufus.ie/ can be used to create flash drives for installing Ubuntu systems

**Comment by silverv** [comment]
I don't have time to help you other than that.

**Comment by silverv** [comment]
Maybe it is a bad cable though?

**Comment by silverv** [comment]
or maybe there is no CAN traffic at all

**Comment by sainquake** [comment]
Finally we found out where the problem is. It is in the Sniffer. The point is that there are different types of SLCAN that can be:
- [https://python-can.readthedocs.io/en/master/interfaces/serial.html](https://python-can.readthedocs.io/en/master/interfaces/serial.html)
- [https://python-can.readthedocs.io/en/master/interfaces/slcan.html](https://python-can.readthedocs.io/en/master/interfaces/slcan.html)

I dont know what is used in my sniffer, but it works on babel. It would be great if you could add a way to select the SLCAN type or automatically define which type is used by the hardware.

**Comment by pavel-kirienko** [comment]
The first one is not SLCAN.
